FROM ruby:2.6.5-slim

RUN apt-get update && apt-get install -y curl gnupg
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" > /etc/apt/sources.list.d/pgdg.list
RUN curl -q https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -


RUN apt-get -y update \
  && apt-get install -y --fix-missing --no-install-recommends -qq \
  build-essential \
  vim \
  ssh \
  postgresql-client-11 \
  libpq5 \
  libpq-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app

COPY Gemfile ./
COPY Gemfile.lock ./
RUN gem install bundler
RUN bundle install

CMD ["rails", "server"]
