version: '3.2'
services:
  app: &app
    build:
      context: .
      dockerfile: docker/Dockerfile.app
      args:
        RUBY_VERSION: "2.6.5"
        PG_MAJOR: "12"
        NODE_MAJOR: "13"
        YARN_VERSION: "1.19.2"
        BUNDLER_VERSION: "2.0.2"
    image: chotto-jigsaw-app

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - bundle:/bundle
    environment:
      BOOTSNAP_CACHE_DIR: /bundle/bootsnap
      DB_HOST: db
      EDITOR: vim
      HISTFILE: /app/log/.bash_history
      NODE_ENV: development
      PSQL_HISTFILE: /app/log/.psql_history
      RAILS_ENV: ${RAILS_ENV:-development}
      REDIS_HOST: redis
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEB_CONCURRENCY: 1
      FIREBASE_CONFIG: ${FIREBASE_CONFIG}
      FIRESTORE_HOST: firestore
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      SEED_USERS: ${SEED_USERS}
    depends_on:
      - db
      - redis

  runner:
    <<: *backend
    command: /bin/bash
    ports:
      - 3000:3000
      - 3002:3002

  web:
    <<: *backend
    command: rails server -b 0.0.0.0
    ports:
      - 3000:3000

  worker:
    <<: *backend
    command: sidekiq -C config/sidekiq.yml

  livereload:
    <<: *backend
    command: guard --no-interactions --plugin LiveReload
    ports:
      - 35729:35729

  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
    ports:
      - 5432

  redis:
    image: redis:5.0-alpine
    volumes:
      - redis:/data
    ports:
      - 6379

  firestore:
    image: kayhide/firestore-emulator:latest
    ports:
      - 8080

  frontend-dev:
    <<: *app
    command: "yarn dev"
    ports:
      - 3035:3035
    volumes:
      - .:/app:cached
      - bundle:/bundle
    environment:
      FIREBASE_CONFIG: ${FIREBASE_CONFIG}
      NODE_ENV: ${NODE_ENV:-development}
      RAILS_ENV: ${RAILS_ENV:-development}
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

volumes:
  bundle:
  postgres:
  redis:
