apiVersion: v1
kind: Service
metadata:
  labels:
    app: chotto-jigsaw-web
  name: chotto-jigsaw-web
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    app: chotto-jigsaw-web
