emulator: &emulator
  emulator_host: <%= ENV.fetch('FIRESTORE_HOST') { "localhost" } %>
  emulator_port: <%= ENV.fetch('FIRESTORE_PORT') { "8080" } %>

development:
  # <<: *emulator
  project_id: chotto-jigsaw-development

test:
  <<: *emulator
  project_id: chotto-jigsaw-test

production:
  project_id: <%= ENV['FIRESTORE_PROJECT_ID'] %>
