default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  port: <%= ENV.fetch("DB_PORT") { "5432" } %>

development:
  <<: *default
  database: chotto_jigsaw_development

test:
  <<: *default
  database: chotto_jigsaw_test

production:
  <<: *default
  database: chotto_jigsaw_production
  username: chotto_jigsaw
  password: <%= ENV['CHOTTO_JIGSAW_DATABASE_PASSWORD'] %>
